#version: "3.9"
#services:
#  mysql-user-service:
#    image: mysql:latest
#    ports:
#      - "3307:3307"
#    container_name: mysql-container
#    networks:
#      - user-net
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_USERNAME: root
#      MYSQL_PASSWORD: root
#      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#
#  user-auth-service:
#    container_name: user-auth-service
#    build: ./
#    networks:
#      - user-net
#    ports:
#      - "8087:8087"
#    depends_on:
#      - mysql-user-service
#    restart: always
#
#networks:
#  user-net:
#    driver: bridge
#
#
